baseURL = 'https://murfitt.net'
languageCode = 'en-gb'
title = 'Dan Murfitt'
sectionPagesMenu = "main"
enableRobotsTXT = true

theme = "PaperMod"

[permalinks]
    blog = '/blog/:title/'

[taxonomies]
    tag = 'tags'

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.instagram]
        disable = false
        simple = true
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = true
    [privacy.vimeo]
        disable = false
        enableDNT = true
        simple = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[build]
    writeStats = true